=== mccutchen/schedulexml-builder/input/schedule.dtd
<!-- Updated 7/5/2006 by Rik Jones to include course.core-code also fixed
     minor requirment errors -->
<!-- Updated 8/8/2007 by Rik Jones to include category -->
<!-- Updated 9/18/2009 by Rik Jones to include DL-type attribute in class -->
<!-- Updated 9/18/2009 by Rik Jones to include schedule-display-options
     attribute in class -->
<!-- Updated 9/28/2009 by Rik Jones to fix some issues with attributes on
     corequisite-section added course-section as required changed course-sec
     to be not required - really should not be here but wanted to be backward
     compatible added credit-type -->

<!ELEMENT schedule              (term|grouping|course)+>
<!ELEMENT term                  (description*,alt-description*,(grouping|course|location|category)+)>
<!ELEMENT grouping              (description*,alt-description*,(term|grouping|location|course)+)>
<!ELEMENT location              (description*,alt-description*,(grouping|course)+)>
<!ELEMENT course                (description*,alt-description*,category*,award*,(class)+)>
<!ELEMENT class                 (description*,alt-description*,charge*,meeting*,xlisting*,corequisite-section*,corequisite-course*)>
<!ELEMENT xlisting              (description*,alt-description*,meeting*)> <!-- Represents another class -->
<!ELEMENT corequisite-section   (description*,alt-description*,meeting*)> <!-- Represents another class -->
<!ELEMENT corequisite-course    (description*,alt-description*,meeting*)> <!-- Represents another course -->
<!ELEMENT meeting               (description*,alt-description*,faculty*)>
<!ELEMENT description           (#PCDATA)>
<!ELEMENT alt-description       (#PCDATA)>
<!ELEMENT faculty               EMPTY>
<!ELEMENT charge                EMPTY>
<!ELEMENT award                 EMPTY>
<!ELEMENT category              EMPTY>

<!ATTLIST schedule
    xmlns           CDATA #REQUIRED
    date-created    CDATA #IMPLIED
    time-created    CDATA #IMPLIED>

<!ATTLIST term
    name            CDATA #REQUIRED
    uri             CDATA #IMPLIED
    sortkey         CDATA #IMPLIED
    year            CDATA #IMPLIED
    start-date      CDATA #IMPLIED
    end-date        CDATA #IMPLIED
    academic-level  CDATA #IMPLIED>

<!ATTLIST location
    name        CDATA #REQUIRED
    uri         CDATA #IMPLIED
    sortkey     CDATA #IMPLIED>

<!ATTLIST grouping
    name        CDATA #REQUIRED
    type        CDATA #REQUIRED
    uri         CDATA #IMPLIED
    sortkey     CDATA #IMPLIED>
<!-- types like "instruction division|rubrik"-->

<!ATTLIST course
    title               CDATA #REQUIRED
    long-title          CDATA #IMPLIED
    uri                 CDATA #IMPLIED
    rubric              CDATA #REQUIRED
    number              CDATA #REQUIRED
    course              CDATA #REQUIRED
    sortkey             CDATA #IMPLIED
    wecm-title          CDATA #IMPLIED
    CEUs                CDATA #IMPLIED
    credit-hours        CDATA #IMPLIED
    core-code           CDATA #IMPLIED
    core-tier-theme     CDATA #IMPLIED>

<!ATTLIST class
    title                       CDATA #REQUIRED
    uri                         CDATA #IMPLIED
    sortkey                     CDATA #IMPLIED
    rubric                      CDATA #REQUIRED
    number                      CDATA #REQUIRED
    section                     CDATA #REQUIRED
    synonym                     CDATA #REQUIRED
    course-section              CDATA #REQUIRED
    location                    CDATA #IMPLIED
    location-code               CDATA #IMPLIED
    start-date                  CDATA #REQUIRED
    end-date                    CDATA #REQUIRED
    credit-type                 CDATA #REQUIRED
    sessions                    CDATA #IMPLIED
    CEUs                        CDATA #IMPLIED
    schedule-type               CDATA #IMPLIED
    status                      CDATA #IMPLIED
    capacity                    CDATA #IMPLIED
    seats-avialable             CDATA #IMPLIED
    weeks                       CDATA #IMPLIED
    dates                       CDATA #IMPLIED
    topic-code                  CDATA #IMPLIED
    tuition                     CDATA #IMPLIED
    xlist-capacity              CDATA #IMPLIED
    wecm-title                  CDATA #IMPLIED
    at-night                    (true|false) "false"
    weekend                     (true|false) "false"
    minimester                  (true|false) "false"
    full-term                   (true|false) "true"
    flex-term                   (true|false) "false"
    self-paced                  (true|false) "false"
    dual-credit                 (true|false) "false"
    jail                        (true|false) "false"
    off-campus                  (true|false) "false"
    out-of-county               (true|false) "false"
    out-of-system               (true|false) "false"
    distance-learning           (true|false) "false"
    online                      (true|false) "false"
    online-primary-class        CDATA #IMPLIED
    fast-track                  (true|false) "false"
    fast-track-term             CDATA #IMPLIED
    flex-term-month             CDATA #IMPLIED
    start-month                 CDATA #IMPLIED
    department                  CDATA #IMPLIED
    department-location         CDATA #IMPLIED
    DL-type                     CDATA #IMPLIED
    schedule-display-options    CDATA #IMPLIED>

<!ATTLIST meeting
    uri         CDATA #IMPLIED
    sortkey     CDATA #IMPLIED
    days        CDATA #REQUIRED
    method      CDATA #REQUIRED
    building    CDATA #REQUIRED
    room        CDATA #REQUIRED
    start-time  CDATA #REQUIRED
    end-time    CDATA #REQUIRED
    times       CDATA #IMPLIED>

<!ATTLIST faculty
    uri             CDATA #IMPLIED
    sortkey         CDATA #IMPLIED
    first-name      CDATA #IMPLIED
    last-name       CDATA #IMPLIED
    middle-name     CDATA #IMPLIED
    email           CDATA #IMPLIED
    phone           CDATA #IMPLIED
    class-load      CDATA #IMPLIED
    url             CDATA #IMPLIED
    vita-id         CDATA #IMPLIED
    vita-url        CDATA #IMPLIED>

<!ATTLIST charge
    uri         CDATA #IMPLIED
    sortkey     CDATA #IMPLIED
    type        CDATA #IMPLIED
    amount      CDATA #IMPLIED>

<!ATTLIST xlisting
    title                   CDATA #IMPLIED
    uri                     CDATA #IMPLIED
    sortkey                 CDATA #IMPLIED
    rubric                  CDATA #REQUIRED
    number                  CDATA #REQUIRED
    section                 CDATA #REQUIRED
    course-sec              CDATA #IMPLIED
    course-section          CDATA #IMPLIED
    synonym                 CDATA #REQUIRED
    schedule-type           CDATA #IMPLIED
    capacity                CDATA #IMPLIED
    weeks                   CDATA #IMPLIED
    dates                   CDATA #IMPLIED
    times                   CDATA #IMPLIED
    credit-type             CDATA #IMPLIED
    location                CDATA #IMPLIED
    location-code           CDATA #IMPLIED
    department              CDATA #IMPLIED
    department-location     CDATA #IMPLIED>

<!ATTLIST corequisite-section
    title                   CDATA #IMPLIED
    uri                     CDATA #IMPLIED
    sortkey               CDATA #IMPLIED
    rubric                CDATA #REQUIRED
    number                CDATA #REQUIRED
    section               CDATA #REQUIRED
    course-sec      CDATA #IMPLIED
    course-section  CDATA #REQUIRED
    synonym               CDATA #REQUIRED
    schedule-type       CDATA #IMPLIED
    capacity              CDATA #IMPLIED
    weeks                   CDATA #IMPLIED
    dates                   CDATA #IMPLIED
    times                   CDATA #IMPLIED
    location              CDATA #IMPLIED
    location-code     CDATA #IMPLIED
    department            CDATA #IMPLIED
    department-location   CDATA #IMPLIED
    credit-type     CDATA #IMPLIED>

<!ATTLIST corequisite-course
    title           CDATA #IMPLIED
    uri             CDATA #IMPLIED
    sortkey         CDATA #IMPLIED
    rubric          CDATA #REQUIRED
    number          CDATA #REQUIRED
    course          CDATA #REQUIRED
    synonym         CDATA #REQUIRED
    schedule-type   DATA #IMPLIED
    capacity        CDATA #IMPLIED
    weeks           CDATA #IMPLIED
    dates           CDATA #IMPLIED
    times           CDATA #IMPLIED
    location        CDATA #IMPLIED
    location-code   CDATA #IMPLIED>

<!ATTLIST award
    code        CDATA #REQUIRED
    catalog     CDATA #REQUIRED
    locations   CDATA #REQUIRED
    title       CDATA #IMPLIED
    degree      CDATA #IMPLIED>

<!ATTLIST category
    code            CDATA #REQUIRED
    description     CDATA #IMPLIED>

=== mccutchen/schedulexml-builder/tch_sandbox/testing/test.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE schedule PUBLIC "http://www.dcccd.edu/SXML/2006/" "http://www.dcccd.edu/SXML/2006/schedule.dtd">
<schedule date-created="7/11/2007" time-created="1:46 PM">
  <term name="2007FA" sortkey="1" year="2007" start-date="8/27/2007" end-date="12/13/2007">
    <location name="200" sortkey="BHC">
      <grouping type="rubric" name="ACCT">
        <course course="ACCT-2301" rubric="ACCT" number="2301" title="Prin Acct I" long-title="Prin Acct I" credit-hours="3.00">
          <class title="Prin Acct I" sortkey="ACCT-2301-2250" synonym="453167" rubric="ACCT" number="2301" section="2250" course-section="ACCT-2301-2250" location-code="200" location="BHC" start-date="09/08/07" end-date="12/08/07" weeks="14" credit-type="CR" status="A" capacity="20" schedule-type="W" weekend="true" full-term="false" start-month="9" at-night="false" minimester="false" flex-term="false" self-paced="false" dual-credit="false" jail="false" off-campus="false" out-of-county="false" out-of-system="false" distance-learning="false" online="false" fast-track="false">
            <meeting days="S" method="LEC" building="BHM" room="M133" start-time="9:00 AM" end-time="12:05 PM">
              <faculty first-name="Patricia" middle-name="Ann" last-name="Bassett" class-load="20.00" />
            </meeting>
          </class>
          <class title="Prin Acct I" sortkey="ACCT-2301-2420" synonym="453171" rubric="ACCT" number="2301" section="2420" course-section="ACCT-2301-2420" location-code="200" location="BHC" start-date="09/04/07" end-date="12/11/07" weeks="15" credit-type="CR" status="A" capacity="25" schedule-type="DL" distance-learning="true" full-term="false" start-month="9" at-night="false" weekend="false" minimester="false" flex-term="false" self-paced="false" dual-credit="false" jail="false" off-campus="false" out-of-county="false" out-of-system="false" online="false" fast-track="false">
            <description>ACCT 2301 requires access to the Internet, e-mail, Microsoft Word and
Excel. The orientation is online and must be completed by the third
class day. Final exam must be taken at an approved monitored testing
site. Enter http://ecampus.dcccd.edu and log in using your seven-digit
student I.D. number as both the user name and password. Contact
claricemccoy@dcccd.edu for information.</description>
            <alt-description>ACCT 2301 requires access to the Internet, e-mail, Microsoft Word and
Excel. The orientation is online and must be completed by the third
class day. Final exam must be taken at an approved monitored testing
site. Enter http://ecampus.dcccd.edu and log in using your seven-digit
student I.D. number as both the user name and password. Contact
claricemccoy@dcccd.edu for information.</alt-description>
            <meeting days="MTWRFSU" method="INET" building="CET" room="INET" start-time="" end-time="">
              <faculty first-name="Clarice" last-name="McCoy" email="cmccoy@dcccd.edu" class-load="20.00" />
            </meeting>
            <xlisting title="Prin Acct I" sortkey="ACCT-2301-9468" synonym="460799" rubric="ACCT" number="2301" section="9468" course-section="ACCT-2301-9468" credit-type="CR" />
          </class>
          <class title="Prin Acct I" sortkey="ACCT-2301-2421" synonym="439972" rubric="ACCT" number="2301" section="2421" course-section="ACCT-2301-2421" location-code="200" location="BHC" start-date="09/04/07" end-date="12/11/07" weeks="15" credit-type="CR" status="A" capacity="25" schedule-type="DL" distance-learning="true" full-term="false" start-month="9" at-night="false" weekend="false" minimester="false" flex-term="false" self-paced="false" dual-credit="false" jail="false" off-campus="false" out-of-county="false" out-of-system="false" online="false" fast-track="false">
            <description>ACCT 2301 requires access to the Internet, e-mail, Microsoft Word
and Excel. The orientation is online and must be completed by the third
class day. Final exam must be taken at an approved monitored
testing site. Enter http://ecampus.dcccd.edu and log in using your
seven-digit student I.D. number as both the user name and password.
Contact claricemccoy@dcccd.edu for information.</description>
            <alt-description>ACCT 2301 requires access to the Internet, e-mail, Microsoft Word
and Excel. The orientation is online and must be completed by the third
class day. Final exam must be taken at an approved monitored
testing site. Enter http://ecampus.dcccd.edu and log in using your
seven-digit student I.D. number as both the user name and password.
Contact claricemccoy@dcccd.edu for information.</alt-description>
            <meeting days="MTWRFSU" method="INET" building="CET" room="INET" start-time="" end-time="">
              <faculty first-name="Clarice" last-name="McCoy" email="cmccoy@dcccd.edu" class-load="20.00" />
            </meeting>
            <xlisting title="Prin Acct I" sortkey="ACCT-2301-9467" synonym="460801" rubric="ACCT" number="2301" section="9467" course-section="ACCT-2301-9467" credit-type="CR" />
          </class>
          <class title="Prin Acct I" sortkey="ACCT-2301-2423" synonym="453173" rubric="ACCT" number="2301" section="2423" course-section="ACCT-2301-2423" location-code="200" location="BHC" start-date="10/01/07" end-date="11/05/07" weeks="6" credit-type="CR" status="A" capacity="37" schedule-type="DL" distance-learning="true" full-term="false" start-month="10" at-night="false" weekend="false" minimester="false" flex-term="false" self-paced="false" dual-credit="false" jail="false" off-campus="false" out-of-county="false" out-of-system="false" online="false" fast-track="false">
            <description>ACCT 2301 requires access to the Internet, e-mail, Microsoft Word and
Excel. The orientation is online and must be completed by the third
class day. Final exam must be taken at an approved monitored testing
site. Enter http://ecampus.dcccd.edu and log in using your seven-digit
student I.D. number as both the user name and password. Contact
claricemccoy@dcccd.edu for information.</description>
            <alt-description>ACCT 2301 requires access to the Internet, e-mail, Microsoft Word and
Excel. The orientation is online and must be completed by the third
class day. Final exam must be taken at an approved monitored testing
site. Enter http://ecampus.dcccd.edu and log in using your seven-digit
student I.D. number as both the user name and password. Contact
claricemccoy@dcccd.edu for information.</alt-description>
            <meeting days="MTWRFSU" method="INET" building="CET" room="INET" start-time="" end-time="">
              <faculty first-name="Clarice" last-name="McCoy" email="cmccoy@dcccd.edu" class-load="20.00" />
            </meeting>
            <xlisting title="Prin Acct I" sortkey="ACCT-2301-9470" synonym="460807" rubric="ACCT" number="2301" section="9470" course-section="ACCT-2301-9470" credit-type="CR" />
          </class>
          <class title="Prin Acct I" sortkey="ACCT-2301-2424" synonym="453175" rubric="ACCT" number="2301" section="2424" course-section="ACCT-2301-2424" location-code="200" location="BHC" start-date="10/01/07" end-date="12/10/07" weeks="11" credit-type="CR" status="A" capacity="37" schedule-type="DL" distance-learning="true" full-term="false" start-month="10" at-night="false" weekend="false" minimester="false" flex-term="false" self-paced="false" dual-credit="false" jail="false" off-campus="false" out-of-county="false" out-of-system="false" online="false" fast-track="false">
            <description>ACCT 2301 requires access to the Internet, e-mail, Microsoft Word and
Excel. The orientation is online and must be completed by the third
class day. Final exam must be taken at an approved monitored testing
site. Enter http://ecampus.dcccd.edu and log in using your seven-digit
student I.D. number as both the user name and password. Contact
claricemccoy@dcccd.edu for information.</description>
            <alt-description>ACCT 2301 requires access to the Internet, e-mail, Microsoft Word and
Excel. The orientation is online and must be completed by the third
class day. Final exam must be taken at an approved monitored testing
site. Enter http://ecampus.dcccd.edu and log in using your seven-digit
student I.D. number as both the user name and password. Contact
claricemccoy@dcccd.edu for information.</alt-description>
            <meeting days="MTWRFSU" method="INET" building="CET" room="INET" start-time="" end-time="">
              <faculty first-name="Clarice" last-name="McCoy" email="cmccoy@dcccd.edu" class-load="20.00" />
            </meeting>
            <xlisting title="Prin Acct I" sortkey="ACCT-2301-9471" synonym="460809" rubric="ACCT" number="2301" section="9471" course-section="ACCT-2301-9471" credit-type="CR" />
          </class>
          <class title="Prin Acct I" sortkey="ACCT-2301-2425" synonym="453183" rubric="ACCT" number="2301" section="2425" course-section="ACCT-2301-2425" location-code="200" location="BHC" start-date="10/24/07" end-date="12/11/07" weeks="8" credit-type="CR" status="A" capacity="37" schedule-type="DL" distance-learning="true" full-term="false" start-month="10" at-night="false" weekend="false" minimester="false" flex-term="false" self-paced="false" dual-credit="false" jail="false" off-campus="false" out-of-county="false" out-of-system="false" online="false" fast-track="false">
            <description>ACCT 2301 requires access to the Internet, e-mail, Microsoft Word and
Excel. The orientation is online and must be completed by the third
class day. Final exam must be taken at an approved monitored testing
site. Enter http://ecampus.dcccd.edu and log in using your seven-digit
student I.D. number as both the user name and password. Contact
claricemccoy@dcccd.edu for information.</description>
